name: bugFinder_FastAPI
channels:
  - defaults
dependencies:
  - python=3.11
  - fastapi
  - uvicorn
  - streamlit
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - pillow
  - requests
  - typing-extensions
  - zlib
  - libtiff
  - libpng
  - lz4-c
  - pyzmq
  - tornado
  - pydantic
  - pyarrow
  - grpcio-tools
  - protobuf
  - retrying
  - pip
  - pip:
    - environs==9.5.0
    - filelock==3.15.4
    - fsspec==2024.6.0
    - grpcio==1.63.0
    - huggingface-hub==0.23.4
    - marshmallow==3.21.3
    - milvus==2.2.16
    - mpmath==1.3.0
    - networkx==3.3
    - packaging==24.1
    - protobuf==5.27.1
    - pymilvus==2.4.4
    - python-dotenv==1.0.1
    - regex==2024.5.15
    - safetensors==0.4.3
    - sentence-transformers==3.0.1
    - sympy==1.12.1
    - threadpoolctl==3.5.0
    - tokenizers==0.19.1
    - torch==2.3.1
    - tqdm==4.66.4
    - transformers==4.41.2
    - tzdata==2024.1
    - ujson==5.10.0
